version: "3.6"

services:
  daledou:
    build: .
    container_name: daledou
    restart: always
    command: python3 main.py --timing
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - .:/code
