# 【yaml】文件格式说明:
# 所有标点符号均使用英文,比如 : -
# 冒号: 与数据之间有一个空格
# 短横线- 与数据之间有一个空格
# 在行首加 # 会注释该行

# ************日常任务配置************

矿洞: floor=1&mode=1
# 开启副本，默认开启 第一层（简单）
# floor=1&mode=1    第一层（简单）
# floor=1&mode=2    第一层（普通）
# floor=1&mode=3    第一层（困难）
# floor=2&mode=1    第二层（简单）
# floor=2&mode=2    第二层（普通）
# floor=2&mode=3    第二层（困难）
# floor=3&mode=1    第三层（简单）
# floor=3&mode=2    第三层（普通）
# floor=3&mode=3    第三层（困难）
# floor=4&mode=1    第四层（简单）
# floor=4&mode=2    第四层（普通）
# floor=4&mode=3    第四层（困难）
# floor=5&mode=1    第五层（简单）
# floor=5&mode=2    第五层（普通）
# floor=5&mode=3    第五层（困难）

历练:
  # 关卡挑战BOSS顺序
  - 6114 # 摩云山     韦小宝
  - 6034 # 林松郊外   令狐冲
  - 6054 # 林松城     丁春秋
  - 6074 # 东海龙宫   丘处机
  - 6094 # 踏云镇     小龙女
  - 6134 # 洞庭湖     扫地僧
  - 6154 # 苍莽山     鹤笔翁
  - 6174 # 玉龙湿地   韦一笑
  - 6194 # 玉龙雪山   赵  敏

幻境: 1
# 1 乐斗村
# 2 林松郊外
# 3 林松城
# 4 东海龙宫
# 5 踏云镇
# 6 摩云山
# 7 洞庭湖
# 8 苍莽山
# 9 玉龙湿地
# 10  玉龙雪山
# 11  狂沙台地
# 12  回声遗迹
# 13  悲叹山丘
# 14  黄沙漩涡
# 15  炎之洞窟
# 16  程管小镇
# 17  花果山
# 18  藏剑山庄
# 19  桃花剑冢
# 20  鹅王的试炼

背包:
  # 使用 -> 在网址找到 id=xxx
  # 如果物品带宝箱字样的不用添加id，脚本自动查找
  - 3030 # 神来拳套(赠)
  - 3176 # 阅历羊皮卷
  - 3356 # 贡献小笼包
  - 3381 # 阅历卷宗
  - 3487 # 巅峰之战二等勋章
  - 3488 # 巅峰之战一等勋章
  - 3503 # 贡献叉烧包
  - 3671 # 资源补给箱
  - 5392 # 3级星石礼盒
  - 6779 # 惊喜锦囊

十二宫: 1000
# 白羊宫  1000
# 金牛宫  1001
# 双子宫  1002
# 巨蟹宫  1003
# 狮子宫  1004
# 处女宫  1005
# 天秤宫  1006
# 天蝎宫  1007
# 射手宫  1008
# 摩羯宫  1009
# 水瓶宫  1010
# 双鱼宫  1011

竞技场: false
# 商店兑换10个，默认不兑换
# 3567  神秘精华  可以用来强化神装技能
# 3568  精武之魂  可以提升神装·神兵的生命加成
# 3569  守护之魂  可以提升神装·神凯的生命加成
# 3573  神兵原石  可以用来进阶神装·神兵
# 3574  软猥金丝  可以用来进阶神装·神铠
# 5435  河洛图书  可以用来提升助阵属性等级

神匠坊:
  # 符石分解
  - 6161 # 破坏·幽月I
  - 6160 # 闪耀·银光I
  - 6159 # 终结·焱炎I
  - 6158 # 洞悉·紫晶I
  # - 6157 # 破坏·流风II
  # - 6156 # 闪耀·流风II
  # - 6155 # 破坏·幽月II
  # - 6154 # 闪耀·幽月II
  # - 6153 # 破坏·银光II
  # - 6152 # 闪耀·银光II
  # - 6151 # 洞悉·焱炎II
  # - 6150 # 洞悉·焱炎II
  # - 6149 # 终结·苍玉II
  # - 6148 # 洞悉·苍玉II
  # - 6147 # 终结·紫晶II
  # - 6146 # 洞悉·紫晶II
  # - 6145 # 破坏·暴风III
  # - 6144 # 闪耀·暴风III
  # - 6143 # 破坏·狂风III
  # - 6142 # 闪耀·狂风III
  # - 6141 # 破坏·霸风III
  # - 6140 # 闪耀·霸风III
  # - 6139 # 破坏·流风III
  # - 6138 # 闪耀·流风III
  # - 6137 # 破坏·灵月III
  # - 6136 # 闪耀·灵月III
  # - 6135 # 破坏·清月III
  # - 6134 # 闪耀·清月III
  # - 6133 # 破坏·锦月III
  # - 6132 # 闪耀·锦月III
  # - 6131 # 破坏·雪月III
  # - 6130 # 闪耀·雪月III
  # - 6129 # 破坏·幽月III
  # - 6128 # 闪耀·幽月III
  # - 6127 # 破坏·银光III
  # - 6126 # 闪耀·银光III
  # - 6125 # 终结·异炎III
  # - 6124 # 洞悉·异炎III
  # - 6123 # 终结·焱炎III
  # - 6122 # 洞悉·焱炎III
  # - 6121 # 终结·烟晶III
  # - 6120 # 洞悉·烟晶III
  # - 6119 # 终结·紫晶III
  # - 6118 # 洞悉·紫晶III

问鼎天下:
  # 淘汰赛、排名赛助威帮派id，默认助威 神阁☆圣域
  淘汰赛: 82494
  排名赛: 82494

帮派商会:
  交易会所:
    # 点击交易 -> 在网址找到 type=0&goods_id=3041
    小体力*10: type=0&goods_id=3001
    大体力*5: type=0&goods_id=3003
    经验药水*5: type=0&goods_id=3014
    大经验药水*1: type=0&goods_id=3015
    经验药水7天*5: type=0&goods_id=3019
    神来拳套*5: type=0&goods_id=3028
    被动经验7天*1: type=0&goods_id=3029
    真体力*5: type=0&goods_id=3041
    经验木简*10: type=1&goods_id=3178
  兑换商店:
    # 点击兑换 -> 在网址找到 type_id=259
    1级狂暴石*1: 251
    1级神愈石*1: 252
    2级狂暴石*1: 253
    1级狂暴石*2: 255
    1级神愈石*2: 256
    1级神愈石*5: 258
    1级狂暴石*10: 259
    1级神愈石*10: 260
    1级日曜石*1: 261

武林盟主: 3
#  默认报名 青铜赛场
# 黄金赛场  1   要求最低战力2000
# 白银赛场  2   要求最低战力1000
# 青铜赛场  3   要求最低战力200

江湖长梦:
  # 选择副本，目前仅支持 柒承的忙碌日常
  # [1, 0] 中的 1 表示柒承的忙碌日常的id，0 表示要通关的次数
  - [1, 0] # 柒承的忙碌日常
  # - [27, 0] # 战乱襄阳
  # - [24, 0] # 时空守护者
  # - [25, 0] # 一骑红尘妃子笑
  # - [26, 0] # 神雕侠侣
  # - [23, 0] # 全真古墓意难平
  # - [22, 0] # 中原武林之危
  # - [21, 0] # 世外桃源梦一场
  # - [20, 0] # 老鹅的圣诞冒险
  # - [7, 0] # 技冠五绝
  # - [19, 0] # 桃花自古笑春风
  # - [28, 0] # 天涯浪子

我的帮派:
  # 帮派守护神要供奉的物品
  - 3043 # 被动经验药水
  - 3014 # 经验药水
  - 3001 # 小体力
  - 3003 # 大体力
  - 3028 # 神来拳套
  - 3089 # 还魂丹

深渊之潮: 1
# 1 崎岖斗界
# 2 魂渡桥
# 3 须臾之河
# 4 曲镜空洞
# 5 光影迷界
# 6 吞厄源头
# 7 渊秘祭坛

门派邀请赛: false
# 商店兑换10个，默认不兑换
# 1246  炼气石      可以用来强化门派上层心法
# 1247  门派强化书  可以用来强化门派武器和技能
# 1248  门派高香    可以用来上香获得门派贡献
# 1249  门派战书    可以用来增加同门切磋和门派邀请赛额外次数
# 1250  门派引荐书  可以用来变更门派

# ************周活动配置************

登录商店: 1223
# 默认兑换 黄金卷轴*1
# 1221  中体力*1
# 1222  真体力*1
# 1223  黄金卷轴*1
# 1224  孙子兵法*1
# 1225  武穆遗书*1
# 1226  神秘精华*1
# 1227  神兵原石*1
# 1228  软猥金丝*1
# 1229  凤凰羽毛*1
# 1230  潜能果实*1
# 1231  上古玉髓*1
# 1232  奔流气息*1

长安盛会: 3036
# 选择黄金卷轴类别（用于第一阶段）
# 3036 黄金卷轴
# 5089 真黄金卷轴

生肖福卡: false
# 把福卡分享给对方的QQ，默认不分享

企鹅吉利兑:
  # 材料兑换优先级
  # 截止日的前一天（最后一个周四）兑换，比如28日结束，那么会在27日完成兑换
  - 1 # 泯灭·烟晶IV
  - 2 # 破坏·银光IV
  - 3 # 洞悉·异炎IV
  - 4 # 破坏·锦月IV
  - 5 # V级万能碎片
  - 6 # 熔炼乌金
  - 7 # 玄铁令
  - 8 # 挑战书
