# ************日常任务配置************

# 开启副本，默认开启 第一层（简单）
矿洞:
  floor: 1
  mode: 1
# floor: 1、2、3、4、5分别对应第一~第五层
# mode: 1、2、3分别对应简单、普通、困难

# 选择关卡BOSS
# 由于取消自动使用活力药水，所以至多只会挑战前两关卡个BOSS，按自己喜好改变下列顺序
历练:
  - 6134 # 洞庭湖     扫地僧
  - 6154 # 苍莽山     鹤笔翁
  - 6114 # 摩云山     韦小宝
  - 6034 # 林松郊外   令狐冲
  - 6054 # 林松城     丁春秋
  - 6074 # 东海龙宫   丘处机
  - 6094 # 踏云镇     小龙女
  - 6174 # 玉龙湿地   韦一笑
  - 6194 # 玉龙雪山   赵  敏

# 选择关卡，默认 乐斗村
幻境: 1
# 1 乐斗村
# 2 林松郊外
# 3 林松城
# 4 东海龙宫
# 5 踏云镇
# 6 摩云山
# 7 洞庭湖
# 8 苍莽山
# 9 玉龙湿地
# 10 玉龙雪山
# 11 狂沙台地
# 12 回声遗迹
# 13 悲叹山丘
# 14 黄沙漩涡
# 15 炎之洞窟
# 16 程管小镇
# 17 花果山
# 18 藏剑山庄
# 19 桃花剑冢
# 20 鹅王的试炼

# 商店兑换10个，支持多个材料兑换
# 默认兑换真黄金卷轴*10*2个
会武:
  1263: 2
  # 1263 真黄金卷轴
  # 1264 修为丹
  # 1265 试炼书

# 背包匹配的物品全部使用
# 物品支持全字、部分名称及正则匹配（注意转义字符）
背包:
  - 盒           # 匹配仙侠盲盒、周年壕气礼盒...
  - 箱           # 匹配资源补给箱、魂珠碎片宝箱...
  - 锦囊         # 匹配惊喜锦囊、武神坛银锦囊...
  - 信物         # 匹配蔡八斗的信物、吕青橙的信物...
  - 包           # 匹配贡献小笼包、贡献叉烧包...
  - 勋章         # 匹配巅峰之战一等勋章、巅峰之战二等勋章...
  - \d+天        # 匹配邪神30天、菜菜7天...
  - 生命洗刷刷    # 匹配生命洗刷刷（不支持其它洗刷刷）
  - 神来拳套\(赠\)
  - 大力丸
  - 活血散
  - 迅捷珠
  - 风之息
  - 减伤药水
  - 翡翠银戒
  - 阅历羊皮卷

# 选择关卡，默认白羊宫
十二宫: 1000
# 白羊宫 1000
# 金牛宫 1001
# 双子宫 1002
# 巨蟹宫 1003
# 狮子宫 1004
# 处女宫 1005
# 天秤宫 1006
# 天蝎宫 1007
# 射手宫 1008
# 摩羯宫 1009
# 水瓶宫 1010
# 双鱼宫 1011

# 竞技点商店兑换10个，默认不兑换
竞技场: null
# 3567 神秘精华 可以用来强化神装技能
# 3568 精武之魂 可以提升神装·神兵的生命加成
# 3569 守护之魂 可以提升神装·神凯的生命加成
# 3573 神兵原石 可以用来进阶神装·神兵
# 3574 软猥金丝 可以用来进阶神装·神铠
# 5435 河洛图书 可以用来提升助阵属性等级

# 符石分解，默认分解I类
神匠坊:
  - 6161 # 破坏·幽月I
  - 6160 # 闪耀·银光I
  - 6159 # 终结·焱炎I
  - 6158 # 洞悉·紫晶I
  # - 6157 # 破坏·流风II
  # - 6156 # 闪耀·流风II
  # - 6155 # 破坏·幽月II
  # - 6154 # 闪耀·幽月II
  # - 6153 # 破坏·银光II
  # - 6152 # 闪耀·银光II
  # - 6151 # 洞悉·焱炎II
  # - 6150 # 洞悉·焱炎II
  # - 6149 # 终结·苍玉II
  # - 6148 # 洞悉·苍玉II
  # - 6147 # 终结·紫晶II
  # - 6146 # 洞悉·紫晶II
  # - 6145 # 破坏·暴风III
  # - 6144 # 闪耀·暴风III
  # - 6143 # 破坏·狂风III
  # - 6142 # 闪耀·狂风III
  # - 6141 # 破坏·霸风III
  # - 6140 # 闪耀·霸风III
  # - 6139 # 破坏·流风III
  # - 6138 # 闪耀·流风III
  # - 6137 # 破坏·灵月III
  # - 6136 # 闪耀·灵月III
  # - 6135 # 破坏·清月III
  # - 6134 # 闪耀·清月III
  # - 6133 # 破坏·锦月III
  # - 6132 # 闪耀·锦月III
  # - 6131 # 破坏·雪月III
  # - 6130 # 闪耀·雪月III
  # - 6129 # 破坏·幽月III
  # - 6128 # 闪耀·幽月III
  # - 6127 # 破坏·银光III
  # - 6126 # 闪耀·银光III
  # - 6125 # 终结·异炎III
  # - 6124 # 洞悉·异炎III
  # - 6123 # 终结·焱炎III
  # - 6122 # 洞悉·焱炎III
  # - 6121 # 终结·烟晶III
  # - 6120 # 洞悉·烟晶III
  # - 6119 # 终结·紫晶III
  # - 6118 # 洞悉·紫晶III

# 淘汰赛、排名赛助威帮派id，默认助威 神阁☆圣域
问鼎天下:
  淘汰赛: 82494
  排名赛: 82494

# 选择交易和兑换物品
# 物品支持全字、部分名称及正则匹配（注意*要转义\*）
帮派商会:
  交易会所:
    - 体力 # 匹配真体力、大体力、小体力等含有体力的物品
    - 经验 # 匹配经验药水、经验木筒等含有经验的物品
    - 悟性丹\*20 # 匹配悟性丹*20
    - 百炼钢 # 匹配百炼钢
  兑换商店:
    - V碎片 # 匹配xx.xxV碎片*1

# 默认报名 青铜赛场
武林盟主: 3
# 黄金赛场 1 要求最低战力2000
# 白银赛场 2 要求最低战力1000
# 青铜赛场 3 要求最低战力200

# 柒承的忙碌日常副本每天挑战次数，为0表示不挑战
江湖长梦: 0

# 帮派守护神供奉每个物品5次
我的帮派:
  - 3023 # 力量洗刷刷
  - 3024 # 敏捷洗刷刷
  - 3025 # 速度洗刷刷
  - 3043 # 被动经验药水
  - 3014 # 经验药水
  - 3001 # 小体力
  - 3003 # 大体力
  - 3028 # 神来拳套
  - 3074 # 追魂锁链
  - 3089 # 还魂丹
  - 3100 # 还童卷轴
  - 3871 # 百炼钢
  - 5391 # 佣兵天赋丹

# 选择关卡，默认崎岖斗界
深渊之潮: 1
# 1 崎岖斗界
# 2 魂渡桥
# 3 须臾之河
# 4 曲镜空洞
# 5 光影迷界
# 6 吞厄源头
# 7 渊秘祭坛

# 商店兑换10个，支持多个材料兑换
# 默认兑换炼气石*10*2个
门派邀请赛:
  1246: 2
  # 1246 炼气石     可以用来强化门派上层心法
  # 1247 门派强化书  可以用来强化门派武器和技能
  # 1248 门派高香    可以用来用来上香获得门派贡献
  # 1249 门派战书    可以用来增加同门切磋和门派邀请赛额外次数
  # 1250 门派引荐书  可以用来变更门派

# ************周活动配置************

# 默认兑换 黄金卷轴*1
登录商店: 1223
# 1221 中体力*1
# 1222 真体力*1
# 1223 黄金卷轴*1
# 1224 孙子兵法*1
# 1225 武穆遗书*1
# 1226 神秘精华*1
# 1227 神兵原石*1
# 1228 软猥金丝*1
# 1229 凤凰羽毛*1
# 1230 潜能果实*1
# 1231 上古玉髓*1
# 1232 奔流气息*1

# 选择黄金卷轴类别（用于第一阶段）
长安盛会: 3036
# 3036 黄金卷轴
# 5089 真黄金卷轴

# 把福卡分享给对方的QQ，默认不分享
生肖福卡: null

# 材料兑换优先级
# 截止日的前一天（最后一个周四）兑换，比如28日结束，那么会在27日完成兑换
企鹅吉利兑:
  - 7 # 玄铁令
  - 6 # 熔炼乌金
  - 5 # V级万能碎片
  - 1 # 泯灭·烟晶IV
  - 2 # 破坏·银光IV
  - 3 # 洞悉·异炎IV
  - 4 # 破坏·锦月IV
  - 8 # 挑战书
