# ************日常任务配置************

# 副本默认开启 第一层（简单）
矿洞:
  floor: 1 # 1、2、3、4、5分别对应第一~第五层
  mode: 1 # 1、2、3分别对应简单、普通、困难

# 选择关卡BOSS，活力药水不会自动使用
历练:
  - 6114 # 摩云山    韦小宝碎片
  - 6134 # 洞庭湖    扫地僧碎片
  - 6154 # 苍莽山    鹤笔翁碎片
  - 6034 # 林松郊外  令狐冲碎片
  - 6054 # 林松城    丁春秋碎片
  - 6074 # 东海龙宫  丘处机碎片
  - 6094 # 踏云镇    小龙女碎片
  - 6174 # 玉龙湿地  韦一笑碎片
  - 6194 # 玉龙雪山  赵  敏碎片

# 会武商店兑换
会武:
  # week 指兑换星期，number 指兑换数量
  真黄金卷轴:
    id: 1263
    week: [1, 2, 3, 4, 5, 6, 7] # 周一~周日兑换
    number: 10
  修为丹:
    id: 1264
    week: [1, 2, 3, 4, 5, 6, 7] # 周一~周日兑换
    number: 0
  试炼书:
    id: 1265
    week: [1, 2, 3] # 周一、二、三兑换
    number: 1

# 背包使用
背包:
  # 物品支持全字、部分名称及正则匹配（注意转义字符）
  - 盒           # 匹配仙侠盲盒、周年壕气礼盒...
  - 箱           # 匹配资源补给箱、魂珠碎片宝箱...
  - 锦囊         # 匹配惊喜锦囊、武神坛银锦囊...
  - 信物         # 匹配蔡八斗的信物、吕青橙的信物...
  - 包           # 匹配贡献小笼包、贡献叉烧包...
  - 勋章         # 匹配巅峰之战一等勋章、巅峰之战二等勋章...
  - \d+天        # 匹配邪神30天、菜菜7天...
  - 生命洗刷刷    # 匹配生命洗刷刷（不支持其它洗刷刷）
  - 神来拳套\(赠\)
  - 大力丸
  - 活血散
  - 迅捷珠
  - 风之息
  - 减伤药水
  - 翡翠银戒
  - 阅历羊皮卷

# 默认分解 I类
神匠坊:
  - 6161 # 破坏·幽月I
  - 6160 # 闪耀·银光I
  - 6159 # 终结·焱炎I
  - 6158 # 洞悉·紫晶I
  # - 6157 # 破坏·流风II
  # - 6156 # 闪耀·流风II
  # - 6155 # 破坏·幽月II
  # - 6154 # 闪耀·幽月II
  # - 6153 # 破坏·银光II
  # - 6152 # 闪耀·银光II
  # - 6151 # 洞悉·焱炎II
  # - 6150 # 洞悉·焱炎II
  # - 6149 # 终结·苍玉II
  # - 6148 # 洞悉·苍玉II
  # - 6147 # 终结·紫晶II
  # - 6146 # 洞悉·紫晶II
  # - 6145 # 破坏·暴风III
  # - 6144 # 闪耀·暴风III
  # - 6143 # 破坏·狂风III
  # - 6142 # 闪耀·狂风III
  # - 6141 # 破坏·霸风III
  # - 6140 # 闪耀·霸风III
  # - 6139 # 破坏·流风III
  # - 6138 # 闪耀·流风III
  # - 6137 # 破坏·灵月III
  # - 6136 # 闪耀·灵月III
  # - 6135 # 破坏·清月III
  # - 6134 # 闪耀·清月III
  # - 6133 # 破坏·锦月III
  # - 6132 # 闪耀·锦月III
  # - 6131 # 破坏·雪月III
  # - 6130 # 闪耀·雪月III
  # - 6129 # 破坏·幽月III
  # - 6128 # 闪耀·幽月III
  # - 6127 # 破坏·银光III
  # - 6126 # 闪耀·银光III
  # - 6125 # 终结·异炎III
  # - 6124 # 洞悉·异炎III
  # - 6123 # 终结·焱炎III
  # - 6122 # 洞悉·焱炎III
  # - 6121 # 终结·烟晶III
  # - 6120 # 洞悉·烟晶III
  # - 6119 # 终结·紫晶III
  # - 6118 # 洞悉·紫晶III

# 华山论剑荣誉兑换
华山论剑:
  # number 指兑换数量
  钻石:
    id: 6857
    number: 375
  侠士修身录:
    id: 6347
    number: 100
  侠士手记:
    id: 6348
    number: 80
  重出江湖令:
    id: 6349
    number: 0
  斗神符:
    id: 3090
    number: 0

# 淘汰赛、排名赛助威帮派id，默认助威 神阁☆圣域
问鼎天下:
  淘汰赛: 82494
  排名赛: 82494

# 帮派商会交易及兑换物品
帮派商会:
  # 物品支持全字、部分名称及正则匹配（注意*要转义\*）
  交易会所:
    - 体力 # 匹配真体力、大体力、小体力等含有体力的物品
    - 经验 # 匹配经验药水、经验木筒等含有经验的物品
    - 悟性丹\*20 # 匹配悟性丹*20
    - 百炼钢 # 匹配百炼钢
  兑换商店:
    - V碎片 # 匹配xx.xxV碎片*1

# 默认报名 青铜赛场
武林盟主: 3
# 黄金赛场 1 要求最低战力2000
# 白银赛场 2 要求最低战力1000
# 青铜赛场 3 要求最低战力200

# 帮派守护神供奉
我的帮派:
  - 3043 # 被动经验药水
  - 3014 # 经验药水
  - 3001 # 小体力
  - 3003 # 大体力
  - 3028 # 神来拳套
  - 3074 # 追魂锁链
  - 3089 # 还魂丹
  - 3100 # 还童卷轴
  - 3871 # 百炼钢
  - 5391 # 佣兵天赋丹

深渊之潮:
  深渊秘境: 1
    # 1 崎岖斗界
    # 2 魂渡桥
    # 3 须臾之河
    # 4 曲镜空洞
    # 5 光影迷界
    # 6 吞厄源头
    # 7 渊秘祭坛
  许愿帮铺:
    # 兑换指定数量材料
    气魄之书: 200
    力魄之书: 200
    精魄之书: 200
    英魄之书: 200
    中枢之书: 200
    天冲之书: 200
    灵慧之书: 200
    佣兵天赋丹: 0
    许愿卡: 0
    五星许愿卡碎片: 0
    豆油队长碎片: 88
    定海制作书: 1

时空遗迹:
  异兽洞窟:
    # 优先扫荡否则挑战
    - 5 # 异兽母巢
    - 4 # 异兽元帅
    - 3 # 异兽将领
    - 2 # 异兽战士
    - 1 # 异兽幼崽
  遗迹商店:
    # number 指兑换数量，只能兑换10的倍数
    1: # 特惠区
      日引石:
        id: 1
        number: 100
      月引石:
        id: 2
        number: 100
      星引石:
        id: 3
        number: 100
      舆图:
        id: 4
        number: 40
    2: # 售卖区
      日引石:
        id: 5
        number: 50
      月引石:
        id: 6
        number: 50
      星引石:
        id: 7
        number: 50
      舆图:
        id: 8
        number: 20

# 门派邀请赛商店兑换
门派邀请赛:
  # week 指兑换星期，number 指兑换数量
  炼气石:
    id: 1246
    week: [1, 2, 3, 4, 5, 6, 7] # 周一~周日兑换
    number: 10
  门派强化书:
    id: 1247
    week: [1, 2, 3, 4, 5, 6, 7] # 周一~周日兑换
    number: 0
  门派高香:
    id: 1248
    week: []
    number: 0
  门派战书:
    id: 1249
    week: [3, 4, 5, 6, 7] # 周三~周日兑换
    number: 5
  门派引荐书:
    id: 1250
    week: []
    number: 0

# ************周活动配置************

# 默认兑换 黄金卷轴*1
登录商店: 1223
# 1221 中体力*1
# 1222 真体力*1
# 1223 黄金卷轴*1
# 1224 孙子兵法*1
# 1225 武穆遗书*1
# 1226 神秘精华*1
# 1227 神兵原石*1
# 1228 软猥金丝*1
# 1229 凤凰羽毛*1
# 1230 潜能果实*1
# 1231 上古玉髓*1
# 1232 奔流气息*1

# 选择黄金卷轴类别（用于第一阶段）
长安盛会: 5089
# 3036 黄金卷轴
# 5089 真黄金卷轴

# 福卡分享给指定好友QQ（比如自己小号），默认不分享
生肖福卡: null

# 企鹅吉利兑材料兑换
企鹅吉利兑:
  # 兑换指定数量材料
  玄铁令: 20
  熔炼乌金: 100
  V级万能碎片: 25
  挑战书: 30
